ARG BUILD_FROM=ghcr.io/hassio-addons/base:16.0.0
# hadolint ignore=DL3006
FROM ${BUILD_FROM}

# Build arguments
ARG BUILD_ARCH
ARG BUILD_DATE
ARG BUILD_DESCRIPTION
ARG BUILD_NAME
ARG BUILD_REF
ARG BUILD_REPOSITORY
ARG BUILD_VERSION

VOLUME ["/app/public/"]

# Environment variables
ENV \
    HOME="/root" \
    LANG="C.UTF-8" \
    PS1="$(whoami)@$(hostname):$(pwd)$ " \
    S6_BEHAVIOUR_IF_STAGE2_FAILS=2 \
    S6_CMD_WAIT_FOR_SERVICES=1 \
    TERM="xterm-256color"

# Copy root filesystem
COPY rootfs /

# Set shell
SHELL ["/bin/ash", "-o", "pipefail", "-c"]

WORKDIR /usr/src

# Install base system
ARG BUILD_ARCH=amd64
ARG BASHIO_VERSION="v0.16.2"
ARG S6_OVERLAY_VERSION="3.1.6.2"
ARG TEMPIO_VERSION="2021.09.0"
RUN set -o pipefail \
    && apk add --no-cache \
        yarn=1.22.22-r0 \
        git=2.45.2-r0	 \
        nodejs=20.13.1-r0 \
        tzdata=2024a-r1	\
        python3=3.12.3-r1 \
        make=4.4.1-r2 \
        g++=13.2.1_git20240309-r0 \
    &&  echo "Download Dashy" \
    && git clone https://github.com/Lissy93/dashy.git

WORKDIR /usr/src/dashy
# hadolint ignore=DL3060
RUN yarn install --ignore-engines --immutable --no-cache --network-timeout 300000 --network-concurrency 1 \
    && yarn build --mode production --no-clean 

# Expose the port
EXPOSE ${PORT}

# Labels
LABEL \
  io.hass.name="${BUILD_NAME}" \
  io.hass.description="${BUILD_DESCRIPTION}" \
  io.hass.arch="${BUILD_ARCH}" \
  io.hass.type="addon" \
  io.hass.version=${BUILD_VERSION} \
  io.hass.base.version="1.11.1" \
  io.hass.base.name="alpine" \
  io.hass.base.image="hassioaddons/base" \
  maintainer="Benoit Anastay <benoit@anastay.dev>" \
  org.opencontainers.image.title="${BUILD_NAME}" \
  org.opencontainers.image.description="${BUILD_DESCRIPTION}" \
  org.opencontainers.image.vendor="Home Assistant Community Add-ons" \
  org.opencontainers.image.authors="Benoit Anastay <benoit@anastay.dev>" \
  org.opencontainers.image.licenses="MIT" \
  org.opencontainers.image.url="https://anastay.dev" \
  org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
  org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" \
  org.opencontainers.image.created=${BUILD_DATE} \
  org.opencontainers.image.revision=${BUILD_REF} \
  org.opencontainers.image.version=${BUILD_VERSION}